name: flutter_validation
description: Ready localized validation messages.
version: 1.0.9  # Increment version
homepage: https://github.com/Bassamhakimi/flutter_validation

environment:
  sdk: ">=3.0.0 <4.0.0"  # Updated for Dart 3
  # flutter: ">=3.0.0"  # Updated Flutter constraint

dependencies:
  flutter:
    sdk: flutter
  phone_numbers_parser: ^9.0.3
  form_field_validator:
    git:
      url: https://github.com/Bassamhakimi/form_field_validator.git
      ref: nested_multi_validator
  validation_localizations:
    git:
      url: https://github.com/Bassamhakimi/flutter-localizations.git
      path: packages/validation_localizations
      ref: updated-intl  # You'll need to update this package too
